### ISSUE TITLE
Update app.js in backend

### ISSUE THREAD

**Issue by capalvarez** [niclabs/ratadns-visualization#2]
There's a lot of deprecated code in app.js that needs to be eliminated:
- info end point was replaced by processing on client.
- app.use(/sse,..) can be replaced by  app.get(/sse,..)

**Comment by madestro** [comment]
¿qué pasó con esto?

**Comment by franchoco** [comment]
Work in progress. De hecho, estamos migrando este código en node.js a [go](https://golang.org/).

**Comment by franchoco** [comment]
As this codebase is deprecated, I'm closing. New codebase is here: https://github.com/niclabs/ratadns-gopher
